idf_component_register(
    SRCS
        "main.cpp"
        "src/pump_state_machine.cpp"
        "src/pump_command_handler.cpp"
        "src/pump_status_reporter.cpp"
        "src/contactor_controller.cpp"
        "src/pump_led_controller.cpp"
        "src/pump_controller.cpp"
    INCLUDE_DIRS
        "include"
        "include/interfaces"
    REQUIRES
        idf_hals
        smart-farm-common
        espnow_manager
        ui_inputs
        time_manager
        driver
        esp_timer
        nvs_flash
        freertos
)
